--- #YAML:1.0
name:               WWW-Correios-CEP
version:            0.02
abstract:           Perl extension for extract address from CEP (zip code) number
author:
    - rentocron <rentocron@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::TreeBuilder::XPath:  0.01
    LWP:                  0.01
    LWP::UserAgent:       0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
